#!/usr/bin/env node
// After `forge build`: copy ABIs + creation bytecode into the frontend so Vercel never needs Foundry.
//   node scripts/export-abi.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const NAMES = ['TreeToken', 'VerifierRegistry', 'TreeNFT', 'StakingRewards', 'VerificationBounty', 'BurnVault'];
// export identifiers, e.g. TreeNFT -> treeNftAbi
const IDENT = { TreeToken: 'treeToken', VerifierRegistry: 'verifierRegistry', TreeNFT: 'treeNft', StakingRewards: 'stakingRewards', VerificationBounty: 'verificationBounty', BurnVault: 'burnVault' };
const outDir = join(root, 'frontend/src/generated');
mkdirSync(outDir, { recursive: true });

let ts = '// AUTO-GENERATED by scripts/export-abi.mjs — do not edit. Re-run after changing contracts.\n\n';
const bytecode = {};
for (const name of NAMES) {
  const art = JSON.parse(readFileSync(join(root, 'out', `${name}.sol`, `${name}.json`), 'utf8'));
  ts += `export const ${IDENT[name]}Abi = ${JSON.stringify(art.abi)} as const;\n\n`;
  bytecode[name] = art.bytecode.object;
}
writeFileSync(join(outDir, 'abis.ts'), ts);
writeFileSync(join(outDir, 'bytecode.json'), JSON.stringify(bytecode, null, 2) + '\n');
console.log(`exported ${NAMES.length} ABIs + bytecode -> frontend/src/generated`);
